
public class Informacion extends javax.swing.JFrame {

    /**
     * Creates new form Informacion
     */
    public Informacion() {
        initComponents();
        setLocationRelativeTo(null);
        fotos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Bttregresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 300));
        jPanel1.setLayout(null);

        Bttregresar.setBackground(new java.awt.Color(0, 153, 102));
        Bttregresar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Bttregresar.setText("REGRESAR");
        Bttregresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BttregresarMouseClicked(evt);
            }
        });
        jPanel1.add(Bttregresar);
        Bttregresar.setBounds(260, 250, 160, 30);

        jLabel1.setBackground(new java.awt.Color(51, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BIENVENIDO");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 10, 410, 60);

        jLabel2.setForeground(new java.awt.Color(0, 153, 102));
        jLabel2.setText("NOMBRES:  ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 60, 200, 30);

        jLabel3.setForeground(new java.awt.Color(0, 153, 102));
        jLabel3.setText("APELLIDOS");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 120, 200, 30);

        jLabel4.setText("Carlos José  ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 90, 200, 30);

        jLabel5.setText(" Blanco Guzmán ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 150, 200, 30);

        jLabel6.setText("202100250 ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 210, 200, 30);

        jLabel7.setForeground(new java.awt.Color(0, 153, 102));
        jLabel7.setText("CARNET:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 180, 200, 30);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(jLabel8);
        jLabel8.setBounds(220, 80, 250, 150);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BttregresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BttregresarMouseClicked
        Login login= new Login ();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BttregresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Informacion().setVisible(true);
            }
        });
    }

     public void fotos(){
    this.setLocationRelativeTo(this);    
    rsscalelabel.RSScaleLabel.setScaleLabel(jLabel8, "src/imagenes/programador.png");

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bttregresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
